services:
  api-service:
    container_name: api-container-nailshop
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8090:8080'
    networks:
      - backend

  redis:
    image: redis:6.2
    container_name: my-redis
    hostname: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - backend

  mysqldb:
    image: mysql:8.0.42
    container_name: mysql-springboot-container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nailshop
    ports:
      - 3306:3306
    volumes:
      - mysql-springboot-data:/var/lib/mysql
      - mysql-springboot-config:/etc/mysql/conf.d
    networks:
      - backend

networks:
  backend:
    name: springboot-app-network

volumes:
  mysql-springboot-data:
  mysql-springboot-config: