services:
  api-service:
    container_name: api-container-nailshop
    build:
      context: ./
      dockerfile: Dockerfile


    env_file:
      - .env
    ports:
      - '8090:8080'
    networks:
      - backend
  redis:
    image: redis:6.2-alpine
    container_name: my-redis-stack
    hostname: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB;FLUSHALL
    networks:
      - backend