services:
  api-service:
    container_name: api-container-nailshop
    build:
      context: ./
      dockerfile: Dockerfile


    env_file:
      - .env
    ports:
      - '8090:8080'
    networks:
      - backend
  redis:
    image: redis:6.2-alpine
    container_name: my-redis-stack
    hostname: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB;FLUSHALL
    networks:
      - backend

  mysqldb:
    image: mysql:8.0.36-debian
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=notes
    ports:
      - "3370:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1.sql
      - db:/var/lib/mysql