// constants/keywords.js
export const keywords = [
    "Combo làm móng",
    "Combo sơn móng tay",
    "Sơn móng tay chuyên nghiệp",
    "Đá trang trí móng",
    "Nơ đính móng",
    "Bướm đính móng tay",
    "Keo dán móng tay",
    "Dũa móng tay",
    "Sơn gel cho móng tay",
    "Móng tay đính đá",
    "Phụ kiện làm móng",
    "Kéo cắt móng tay",
    "Móng tay đẹp",
    "Sơn móng tay nhanh khô",
    "Hoa đính móng tay",
    "Nail box cute",
    "Đính đá",
    "Nail box tết",
    "Nail box đính hoa",
    "Nail box đơn giản",
    "Nail box nữ tính",
    "Nail box Trắng gạo",
    "Nail box kim cương",
    "Màu hồng",
    "Màu chery",
    "Màu trắng sữa",
    "Nail box lấp lánh",
    "Hồng cẩm thạch",
    "Nail box sang trọng",
    "Nail box màu đỏ",
    "Nailbox xinh",
    "Nail box xinh",
    "Nailbox cute",
    "Dũa",
    "Kéo cắt",
    "Keo dán",
    "Gel móng",
    "Sơn bóng",
    "Nail box tết",
    "Nail box hoa đào",
    "Nail box thiết kế",
    "Nail box design",
    "Nail box tết 2025",
    "Nail box thiết kế sang chảnh",
    "Nail box ngắn",
    "Nail box dài",
    "Đính đá lấp lánh",
    "Nail box lấp lánh"
];
