server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysqldb:3307/nailShop
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
      file-size-threshold: 2KB
  data:
    redis:
      host: "redis"
      port: 6379

payos:
  client-id: "016bd9cc-e92c-46c0-9704-fd25ef18a68b"
  api-key: "2e0123f4-3341-486d-9bb5-947a1a83435f"
  checksum-key: "81a821b97ca81ee954423f04b11f581a5db31fff2caab90b650dbb733330961f"

cloudinary:
  cloud-name: "doslvje9p"
  api-key: "111261246971633"
  api-secret: "lMdfdvz3SsDnpHJA_WDBtRQmFKU"

jwt:
  secret-key: "803ccb9767523d85485cb85e6310e73b34929e7df240d51fb5c9606a9cd94148"
  refresh-key: "04efcb14e6e81940dde1c386ad894d63fc5428a3749185aa70b1e5b82faf8ed7"